### ISSUE TITLE
Dark Mode 

### ISSUE THREAD

**Issue by sachinsenal0x64** [Zeioth/markmap.nvim#11]
Hey, nice project, any way to configure the background color scheme?

**Comment by Zeioth** [comment]
@sachinsenal0x64 sorry for taking a bit to notice your message; The easiest way is to use the browser extension [DarkReader](https://addons.mozilla.org/es/firefox/addon/darkreader/) (also available on chrome).

If you want to apply dark mode to one specific page, you can use [Stylus](https://addons.mozilla.org/es/firefox/addon/styl-us/) instead. Which you can use to modify the CSS code of a particular page.
