### ISSUE TITLE
Plugin currently broken on Windows

### ISSUE THREAD

**Issue by MarcoBuess** [Zeioth/markmap.nvim#12]
`open` and `watch` currently don't work anymore. I suspect an issue with the temp path, that could've been introduced in d9955091418b214abdee4c042ce91c3a30cb9108. When you run `MarkmapWatch` it creates a file named `--watch` in the `cwd`. This could be because no default opts are provided. So if you don't explictly configure the paths in your options it will lead to a "" situation.

**Comment by MarcoBuess** [comment]
A `M.default_opts` could be provided so that when `M.setup()` is called you could go something like 
```lua
M.default_opts = { ... }
M.setup = function(opts)
    local opts = opts or M.default_opts

   -- Or even merge or overwrite with something like
   for k,v in pairs(opts) do M.default_opts[k] = v end
```

**Comment by Zeioth** [comment]
Thank you so much for reporting @MarcoBuess. [I fucked up a copy paste](https://github.com/Zeioth/markmap.nvim/commit/e2e449f54105fbca86a129d5dfa1e9a2deb2392d) during the refactor.

All should be working fine again.

**Comment by MarcoBuess** [comment]
@Zeioth The issue sill persists. It is still creating a `--watch` file and trying to open that in the current directory. 😞

**Comment by MarcoBuess** [comment]
@Zeioth  Looks like `vim.g.markmap_config` is not what you would expect. I'm getting the following back as config in `init.lua`:
```lua
{
  grace_period = 3600000,
  markmap_cmd = "markmap.cmd",
  set = <function 1>
}
```
None of the options seem to get set. Therefore `--watch` will be the first parameter for `-o` instead of the temp folder. Is there any particular reason why you're using globals vs. just returning a table with the default options from `set()`?

**Comment by MarcoBuess** [comment]
I found the bug... Will submit a PR to fix it shortly.
