### ISSUE TITLE
Bug: using jobstart({}) causes problems on Android

### ISSUE THREAD

**Issue by Zeioth** [Zeioth/markmap.nvim#13]
## Description

The reason is 

* `jobstart("mytask")` runs the task in shell.
* `jobstart({ "mytask" })` runs the task directly in the operative system.

That means if you are defining your PATH in the shell, it won't be available, like it's the case on termux. This provokes termux can't find the executable.

### Option 1
* Let's try to run it without `{}`. Windows shouldn't be stupid enough to spawn a shell process. Ideally neovim takes care of it.

### Option 2
Use this option if 1 don't do the trick.

* Instead of running jobstart directly, create a wrapper, so we can choose one or the other depending the OS.
* That way we could run directly on windows, and on shell on UNIX.

**Comment by Zeioth** [comment]
@MarcoBuess could you please test if `v2.1.4` run correctly on windows without spawning a terminal window?
https://github.com/Zeioth/markmap.nvim/releases/tag/v2.1.4

If not, I have the solution but it's gonna require a bit of rework.

**Comment by MarcoBuess** [comment]
I'll try as soon as I can.

**Comment by Zeioth** [comment]
I've gone ahead and implement solution 2. Everything should be fine in `v2.2.0`. Please ping me if you find any bug again ❤️

**Comment by MarcoBuess** [comment]
@Zeioth Wasn't able to test because of #12.
