### ISSUE TITLE
[suggestion] improved watch stop

### ISSUE THREAD

**Issue by MarcoBuess** [Zeioth/markmap.nvim#15]
@Zeioth I wonder if it would make sense, instead of tracking the last execution over a grace period to rather capture the buffer that is currently served and monitor the last write time. Then go and reset the grace period when the buffer was recently written, as one could assume that you are still working on the document. I haven't looked up what the default grace period is but serving just randomly stopped after ~1h when I was still editing the document.

**Comment by MarcoBuess** [comment]
This would also allow for an autocommand that would stop markmap-cli when the served buffer is closed.

**Comment by Zeioth** [comment]
This is the expected behavior, and the simple solution is to just increase the default `grace_period` from 1h to what you need.

But if you see it's not gonna increase complexity too much and want to send a PR go for it. It is a cool feature.

**Comment by MarcoBuess** [comment]
I just wanted to check, if it's cool with you. I'll see what I can do in terms of a PR. 🚀

**Comment by MarcoBuess** [comment]
See #16
