### ISSUE TITLE
Cannot run when filename has spaces (multiple words) 

### ISSUE THREAD

**Issue by tecix** [Zeioth/markmap.nvim#19]
I'm noticing that the  Markmap commands cannot run in Neovim when the filename contains spaces. 
Additionally, a notification would be beneficial to easily spot problems.

**Comment by Zeioth** [comment]
@tecix are you on windows or unix?

**Comment by Zeioth** [comment]
@tecix it should be fixed now! check https://github.com/Zeioth/markmap.nvim/releases/tag/v2.2.3
