### ISSUE TITLE
MarkmapWatchStop not working on windows

### ISSUE THREAD

**Issue by MarcoBuess** [Zeioth/markmap.nvim#9]
Am I getting annoying yet? 😂

**Comment by Zeioth** [comment]
Version released: https://github.com/Zeioth/markmap.nvim/releases/tag/v2.1.1

**Comment by MarcoBuess** [comment]
Seems to be broken still.

**Comment by MarcoBuess** [comment]
It even looks like `MarkmapWatch` is not spawning a job anymore, which I don't quite get.

**Comment by MarcoBuess** [comment]
So it looks like it doesn't kill the node process even on exit. Running `markmap` from CLI showed that the server was still running and occupying port 3000. Command itself seems to work after `node` is killed manually.

**Comment by MarcoBuess** [comment]
Put a PR that addresses the issue on my end.

**Comment by Zeioth** [comment]
Looks good to me. Everything seems to work on my end. Thank you!!
